from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QLabel
from PyQt5.QtCore import pyqtSignal

class ClickableLabel(QLabel):
    clicked = pyqtSignal()

    def __init__(self, parent=None):
        super(ClickableLabel, self).__init__(parent)

    def mousePressEvent(self, event):
        self.clicked.emit()


class Ui_mainWidget(object):
    def setupUi(self, mainWidget):
        mainWidget.setObjectName("mainWidget")
        mainWidget.resize(827, 480)
        self.horizontalLayout = QtWidgets.QHBoxLayout(mainWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.station_combo_box = QtWidgets.QComboBox(mainWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.station_combo_box.sizePolicy().hasHeightForWidth())
        self.station_combo_box.setSizePolicy(sizePolicy)
        self.station_combo_box.setMaximumSize(QtCore.QSize(250, 25))
        self.station_combo_box.setObjectName("station_combo_box")
        self.horizontalLayout_2.addWidget(self.station_combo_box)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.mpl_widget = QtWidgets.QWidget(mainWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mpl_widget.sizePolicy().hasHeightForWidth())
        self.mpl_widget.setSizePolicy(sizePolicy)
        self.mpl_widget.setObjectName("mpl_widget")
        self.verticalLayout.addWidget(self.mpl_widget)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.hideShowPushButton = QtWidgets.QPushButton(mainWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hideShowPushButton.sizePolicy().hasHeightForWidth())
        self.hideShowPushButton.setSizePolicy(sizePolicy)
        self.hideShowPushButton.setMinimumSize(QtCore.QSize(20, 60))
        self.hideShowPushButton.setMaximumSize(QtCore.QSize(10, 60))
        self.hideShowPushButton.setObjectName("hideShowPushButton")
        self.horizontalLayout.addWidget(self.hideShowPushButton)
        self.widget = QtWidgets.QWidget(mainWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(350, 0))
        self.widget.setMaximumSize(QtCore.QSize(350, 16777215))
        self.widget.setObjectName("widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, -1, 10, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.detrendCheckBox = QtWidgets.QCheckBox(self.widget)
        self.detrendCheckBox.setObjectName("detrendCheckBox")
        self.horizontalLayout_9.addWidget(self.detrendCheckBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.highPassCheckBox = QtWidgets.QCheckBox(self.widget)
        self.highPassCheckBox.setObjectName("highPassCheckBox")
        self.horizontalLayout_4.addWidget(self.highPassCheckBox)
        self.highPassLineEdit = QtWidgets.QLineEdit(self.widget)
        self.highPassLineEdit.setObjectName("highPassLineEdit")
        self.horizontalLayout_4.addWidget(self.highPassLineEdit)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.bandPassCheckBox = QtWidgets.QCheckBox(self.widget)
        self.bandPassCheckBox.setObjectName("bandPassCheckBox")
        self.horizontalLayout_5.addWidget(self.bandPassCheckBox)
        self.bandPassStartLineEdit = QtWidgets.QLineEdit(self.widget)
        self.bandPassStartLineEdit.setObjectName("bandPassStartLineEdit")
        self.horizontalLayout_5.addWidget(self.bandPassStartLineEdit)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.bandPassEndLineEdit = QtWidgets.QLineEdit(self.widget)
        self.bandPassEndLineEdit.setObjectName("bandPassEndLineEdit")
        self.horizontalLayout_5.addWidget(self.bandPassEndLineEdit)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_5.addWidget(self.label_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        # self.label_5 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        # self.label_5.setFont(font)
        # self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        # self.label_5.setObjectName("label_5")
        # self.verticalLayout_2.addWidget(self.label_5)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        # self.label_9 = QtWidgets.QLabel(self.widget)
        # self.label_9.setObjectName("label_9")
        # self.horizontalLayout_7.addWidget(self.label_9)
        # self.staLineEdit = QtWidgets.QLineEdit(self.widget)
        # self.staLineEdit.setObjectName("staLineEdit")
        # self.horizontalLayout_7.addWidget(self.staLineEdit)
        # self.label_7 = QtWidgets.QLabel(self.widget)
        # self.label_7.setObjectName("label_7")
        # self.horizontalLayout_7.addWidget(self.label_7)
        self.verticalLayout_2.addLayout(self.horizontalLayout_7)
        # self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        # self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        # self.label_6 = QtWidgets.QLabel(self.widget)
        # self.label_6.setObjectName("label_6")
        # self.horizontalLayout_6.addWidget(self.label_6)
        # self.ltaLineEdit = QtWidgets.QLineEdit(self.widget)
        # self.ltaLineEdit.setObjectName("ltaLineEdit")
        # self.horizontalLayout_6.addWidget(self.ltaLineEdit)
        # self.label_8 = QtWidgets.QLabel(self.widget)
        # self.label_8.setObjectName("label_8")
        # self.horizontalLayout_6.addWidget(self.label_8)
        # self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        # self.ltaStaCheckBox = QtWidgets.QCheckBox(self.widget)
        # self.ltaStaCheckBox.setObjectName("ltaStaCheckBox")
        # self.horizontalLayout_16.addWidget(self.ltaStaCheckBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.EnterPushButton = QtWidgets.QPushButton(self.widget)
        self.EnterPushButton.setMinimumSize(QtCore.QSize(0, 25))
        self.EnterPushButton.setMaximumSize(QtCore.QSize(70, 16777215))
        self.EnterPushButton.setObjectName("EnterPushButton")
        self.horizontalLayout_8.addWidget(self.EnterPushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.horizontalLayout.addWidget(self.widget)
        
        self.crossCorrelateButton = QtWidgets.QPushButton(mainWidget)
        self.crossCorrelateButton.setObjectName("crossCorrelateButton")
        self.crossCorrelateButton.setText("Cross Correlate")
        self.horizontalLayout.addWidget(self.crossCorrelateButton)
        
        self.analyzeButton = QtWidgets.QPushButton("Анализировать P и S волны", mainWidget)
        self.horizontalLayout.addWidget(self.analyzeButton)

        self.loadNewFileButton = QtWidgets.QPushButton("Загрузить новый файл", mainWidget)
        self.loadNewFileButton.clicked.connect(self.open_file_dialog)
        self.horizontalLayout.addWidget(self.loadNewFileButton)  # Размещаем кнопку в горизонтальном layout

        self.retranslateUi(mainWidget)
        QtCore.QMetaObject.connectSlotsByName(mainWidget)

    def retranslateUi(self, mainWidget):
        _translate = QtCore.QCoreApplication.translate
        mainWidget.setWindowTitle(_translate("mainWidget", "Form"))
        self.hideShowPushButton.setText(_translate("mainWidget", ">"))
        self.label_4.setText(_translate("mainWidget", "Фильтрация"))
        self.detrendCheckBox.setText(_translate("mainWidget", "Detrend"))
        self.highPassCheckBox.setText(_translate("mainWidget", "Фильтр верхних частот от"))
        self.label.setText(_translate("mainWidget", "Гц"))
        self.bandPassCheckBox.setText(_translate("mainWidget", "Полосовой фильтр от"))
        self.label_3.setText(_translate("mainWidget", "до"))
        self.label_2.setText(_translate("mainWidget", "Гц"))
        # self.label_5.setText(_translate("mainWidget", "STA/LTA"))
        # self.label_9.setText(_translate("mainWidget", "STA"))
        # self.label_7.setText(_translate("mainWidget", "c"))
        # self.label_6.setText(_translate("mainWidget", "LTA"))
        # self.label_8.setText(_translate("mainWidget", "c"))
        # self.ltaStaCheckBox.setText(_translate("mainWidget", "Активно"))
        self.EnterPushButton.setText(_translate("mainWidget", "Применить"))